app-1  | ERROR:app:Exception on /media/upload [POST]
app-1  | Traceback (most recent call last):
app-1  |   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app
app-1  |     response = self.full_dispatch_request()
app-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
app-1  |   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 919, in full_dispatch_request
app-1  |     rv = self.handle_user_exception(e)
app-1  |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
app-1  |   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request
app-1  |     rv = self.dispatch_request()
app-1  |          ^^^^^^^^^^^^^^^^^^^^^^^
app-1  |   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 902, in dispatch_request
app-1  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
app-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
app-1  |   File "/usr/local/lib/python3.11/site-packages/flask_login/utils.py", line 290, in decorated_view
app-1  |     return current_app.ensure_sync(func)(*args, **kwargs)
app-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
app-1  |   File "/app/routes.py", line 113, in upload_media
app-1  |     file.save(file_path)
app-1  |   File "/usr/local/lib/python3.11/site-packages/werkzeug/datastructures/file_storage.py", line 129, in save
app-1  |     dst = open(dst, "wb")
app-1  |           ^^^^^^^^^^^^^^^
app-1  | PermissionError: [Errno 13] Permission denied: 'uploads/8ec6d21e50f0474ca82c78c751375afd.mp4'
app-1  | ERROR:app:Exception on /media/upload [POST]
app-1  | Traceback (most recent call last):
app-1  |   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app
app-1  |     response = self.full_dispatch_request()
app-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
app-1  |   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 919, in full_dispatch_request
app-1  |     rv = self.handle_user_exception(e)
app-1  |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
app-1  |   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request
app-1  |     rv = self.dispatch_request()
app-1  |          ^^^^^^^^^^^^^^^^^^^^^^^
app-1  |   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 902, in dispatch_request
app-1  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
app-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
app-1  |   File "/usr/local/lib/python3.11/site-packages/flask_login/utils.py", line 290, in decorated_view
app-1  |     return current_app.ensure_sync(func)(*args, **kwargs)
app-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
app-1  |   File "/app/routes.py", line 113, in upload_media
app-1  |     file.save(file_path)
app-1  |   File "/usr/local/lib/python3.11/site-packages/werkzeug/datastructures/file_storage.py", line 129, in save
app-1  |     dst = open(dst, "wb")
app-1  |           ^^^^^^^^^^^^^^^
app-1  | PermissionError: [Errno 13] Permission denied: 'uploads/6e83717c6d244d6d994bc4a328c5ddaa.mp4'